config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :teams
  resources :people

  # Root to projects#index so that the user sees the list of
  # what everyone is working on for a given day
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :team
  has_and_belongs_to_many :projects

  validates :name, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :people
  validates :name, :project_type, :location, :discipline, presence: true
  validates_associated :person_ids
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :project_ids)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :project_type, :location, :time,
                                      :discipline, :person_ids)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VocoMotion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/projects/_form.html.erb
<div class="container col-md-6 col-md-offset-3">
    <%= form_for(project) do |f| %>
    <% if project.errors.any? %>
        <div class="alert alert-warning" id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

    <div class="field form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="field form-group">
        <%= f.label "Type" %>
        <%= f.text_field :project_type, class: 'form-control' %>
    </div>

    <div class="field form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: 'form-control' %>
    </div>

    <div class="field form-group">
        <%= f.label :time %>
        <%= f.text_field :time, class: 'form-control' %>
    </div>

    <div class="field form-group">
        <%= f.label :discipline %>
        <%= f.text_field :discipline, class: 'form-control' %>
    </div>

    <div class="actions">
        <%= f.submit "Submit", class: 'btn btn-default' %>
    </div>
    <% end %>

<!-- Closing </div> is in each action's page. No more orphaned back buttons -->

app/views/projects/edit.html.erb
<h1 class="center">Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

<!-- Closing </div> from _form partial -->
</div>

app/views/projects/index.html.erb
<div class="container col-md-10 col-md-offset-1">
    <% if alert %>
        <div class="alert alert-warning"><%= alert %></div>
    <% end %>
    <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
    <% end %>

    <h1 class="center">Projects</h1>
    <div class="row">
        <table class="table table-condensed col-md-8" id="project-index-table">
            <thead>
                <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Location</th>
                <th>Time</th>
                <th>Discipline</th>
                <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @projects.each do |project| %>
                <tr>
                    <td><%= project.name %></td>
                    <td><%= project.project_type %></td>
                    <td><%= project.location %></td>
                    <td><%= project.time %></td>
                    <td><%= project.discipline %></td>
                    <td><%= link_to 'Show', project, class: 'btn btn-sm btn-primary' %></td>
                    <td>
                        <%= link_to 'Edit',  edit_project_path(project), 
                                class: 'btn btn-sm btn-primary' %>
                    </td>
                    <td>
                        <%= link_to 'Destroy', project, method: :delete, 
                                data: { confirm: 'Are you sure?' },
                                class: 'btn btn-sm btn-danger' %>
                    </td> 
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <br>
    <div class="row">
        <%= link_to 'New Project', new_project_path,
                class: 'btn btn-default col-md-2 col-md-offset-5' %>
    </div>
</div>

app/views/projects/new.html.erb
<h1 class="center">New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

<!-- Closing </div> from _form partial -->
</div>

app/views/projects/show.html.erb
<div class="container col-md-6 col-md-offset-4" id="show-container">
    <% if alert %>
        <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if notice %>
        <div class="alert alert-warning"><%= alert %></div>
    <% end %>
    
    <div class="show-view">
        <p>
        <strong>Name:</strong>
        <%= @project.name %>
        </p>

        <p>
        <strong>Type:</strong>
        <%= @project.project_type %>
        </p>

        <p>
        <strong>Location:</strong>
        <%= @project.location %>
        </p>

        <p>
        <strong>Time:</strong>
        <%= @project.time %>
        </p>

        <p>
        <strong>Discipline:</strong>
        <%= @project.discipline %>
        </p>
    </div>

    <%= link_to 'Edit', edit_project_path(@project) %> |
    <%= link_to 'Back', projects_path %>
</div>